# Generated by Django 3.2.9 on 2022-06-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='', max_length=15)),
                ('book_name', models.CharField(default='', max_length=40)),
                ('author_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
